import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/sections/navbar/Navbar";
import Footer from "@/app/components/sections/footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const navbarLinks = [
    { name: "Login", href: "/loginpage" },
    { name: "Home", href: "/" },
  ];

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar label="Story Teller" links={navbarLinks} />
        {children}
        <Footer
          label="&copy; 2023 My Website. All rights reserved."
          links={[
            { name: "Contatti", href: "/contactpage" },
            { name: "About Me", href: "/aboutme" },
          ]}
        />
      </body>
    </html>
  );
}
