import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";

import "./globals.css";
import { CartProvider } from "@/Context/CartContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <html lang="en">
      <CartProvider>
        <body>
          <Navbar />
          {children}
          <Footer />
        </body>
      </CartProvider>
    </html>
  );
};

export default RootLayout;
